services:
  mysql:
    image: mysql:8.0
    container_name: inventory-mysql

    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service

    ports:
      - "3307:3306"

    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql